<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="rasm">

  <xacro:property name="A1Len" value="0.406"/>
  <xacro:property name="A1Width" value="0.1"/>
  <xacro:property name="A1Height" value="0.1"/>
  <xacro:property name="A2Len" value="0.406"/>
  <xacro:property name="A2Width" value="0.1"/>
  <xacro:property name="A2Height" value="0.1"/>
  <xacro:property name="A1A2LimitLower" value="-0.548"/>
  <xacro:property name="A1A2LimitUpper" value="0.548"/>
  <xacro:property name="base_linkA1LimitLower" value="-0.548"/>
  <xacro:property name="base_linkA1LimitUpper" value="0.548"/>

  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>

  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <link name="base_link" />

  <link name="A1">
    <visual>
      <geometry>
        <box size="${A1Len} ${A1Width} ${A1Height}"/>
      </geometry>
      <origin xyz="${A1Len/2.0} 0 0"/>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="${A1Len} ${A1Width} ${A1Height}"/>
      </geometry>
    </collision>
  </link>

  <link name="A2">
    <visual>
      <geometry>
        <box size="${A2Len} ${A2Width} ${A2Height}"/>
      </geometry>
      <origin xyz="${A2Len/2} 0 ${-A2Height/2}"/>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <box size="${A2Len} ${A2Width} ${A2Height}"/>
      </geometry>
    </collision>
  </link>

  <joint name="A1_to_A2" type="revolute">
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="${A1A2LimitLower}" upper="${A1A2LimitUpper}" velocity="0.5"/>
    <parent link="A1"/>
    <child link="A2"/>
    <origin xyz="${A1Len} 0 ${-A1Height/2}"/>
  </joint>

  <joint name="base_link_to_A1" type="revolute">
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="${base_linkA1LimitLower}" upper="${base_linkA1LimitUpper}" velocity="0.5"/>
    <parent link="base_link"/>
    <child link="A1"/>
    <origin xyz="0 0 0"/>
  </joint>

</robot>
